use serde::{Deserialize, Serialize};

/// Vault metadata stored inside vault repos (.agk/vault.toml)
/// Generated by `agk vault init`
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct VaultManifest {
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(default)]
    pub dependencies: Vec<VaultDependency>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct VaultDependency {
    pub identity: String,
    #[serde(rename = "type")]
    pub dep_type: String,
    pub url: String,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn vault_manifest_round_trip() {
        let manifest = VaultManifest {
            name: "my-vault".to_string(),
            description: Some("A test vault".to_string()),
            version: Some("1.0.0".to_string()),
            dependencies: vec![VaultDependency {
                identity: "base-skills".to_string(),
                dep_type: "github".to_string(),
                url: "https://github.com/org/base-skills".to_string(),
            }],
        };

        let toml_str = toml::to_string_pretty(&manifest).unwrap();
        let loaded: VaultManifest = toml::from_str(&toml_str).unwrap();
        assert_eq!(loaded, manifest);
    }

    #[test]
    fn vault_manifest_minimal() {
        let toml_str = r#"
name = "my-vault"
"#;
        let manifest: VaultManifest = toml::from_str(toml_str).unwrap();
        assert_eq!(manifest.name, "my-vault");
        assert!(manifest.description.is_none());
        assert!(manifest.version.is_none());
        assert!(manifest.dependencies.is_empty());
    }

    #[test]
    fn vault_manifest_with_deps() {
        let toml_str = r#"
name = "enterprise-vault"
description = "Internal enterprise skill vault"
version = "2.3.1"

[[dependencies]]
identity = "core-lib"
type = "github"
url = "https://github.com/acme/core-lib"

[[dependencies]]
identity = "security-base"
type = "github"
url = "https://github.com/acme/security-base"
"#;
        let manifest: VaultManifest = toml::from_str(toml_str).unwrap();

        assert_eq!(manifest.name, "enterprise-vault");
        assert_eq!(
            manifest.description.as_deref(),
            Some("Internal enterprise skill vault")
        );
        assert_eq!(manifest.version.as_deref(), Some("2.3.1"));
        assert_eq!(manifest.dependencies.len(), 2);

        assert_eq!(manifest.dependencies[0].identity, "core-lib");
        assert_eq!(manifest.dependencies[0].dep_type, "github");
        assert_eq!(
            manifest.dependencies[0].url,
            "https://github.com/acme/core-lib"
        );

        assert_eq!(manifest.dependencies[1].identity, "security-base");
        assert_eq!(manifest.dependencies[1].dep_type, "github");
    }
}
